### ISSUE TITLE
Add TODO comments

### ISSUE THREAD

**Issue by dimadeveatii** [labs42io/clean-code-typescript#12]
Provide samples and explanation when/how to use `// TODO` comments (in Comments section).

**Comment by RadicalchAngel** [comment]
//todo

**Comment by dimadeveatii** [comment]
Almost done @RadicalchAngel, but make sure to sum-up what's explained in the original *Clean Code* book in the `readme.md`.

**Comment by dimadeveatii** [comment]
Implemented in this [commit](https://github.com/labs42io/clean-code-typescript/commit/f0ba673e71a14f94e4a962fbf896f7cb788d86ec).
