### ISSUE TITLE
interface-over-type-literal default true

### ISSUE THREAD

**Issue by MSakamaki** [labs42io/clean-code-typescript#19]
although tslint is introduced in [Formatting](https://github.com/labs42io/clean-code-typescript#formatting), since most tslint rules do not override `interface-over-type-literal` and are `true`, contents of [type vs interface](https://github.com/labs42io/clean-code-typescript#type-vs-interface) will error .
(confirming, only **TSLint Clean Code** was `false`)

also [issues](https://github.com/palantir/tslint/issues/3248), it may be deleted from `tslint: recommended` in future, but it has not disappeared at moment.

Important thing is that if you follow the rules of tslint, will most likely result in an error.

need to set `interface-over-type-literal` to `false` as a workaround, should prompt for a trade-off with quality.

should I add this as a supplement to **type vs interface**?

**Comment by dimadeveatii** [comment]
There might be more options like `interface-over-type-literal` that are not inline with principles from *Clean Code*. We should try to avoid transforming this tutorial in a TSLint guide.  

And after all, TSLint is introduced as a recommendation and example of tools that can help make your code *clean*.

**Comment by MSakamaki** [comment]
> There might be more options like `interface-over-type-literal` that are not inline with principles from _Clean Code_. We should try to avoid transforming this tutorial in a TSLint guide.
> And after all, TSLint is introduced as a recommendation and example of tools that can help make your code _clean_.

Okay I agreed !

I will contributing project according to that policy in future.
Thank you for answer!
