### ISSUE TITLE
Set default objects with Object.assign or destructuring

### ISSUE THREAD

**Issue by aleixsuau** [labs42io/clean-code-typescript#38]
Hi,

Could we add the spread operator to this?

````
function createMenu(config: MenuConfig) {
  const menuConfig = {
    title: 'Foo',
    body: 'Bar',
    buttonText: 'Baz',
    cancellable: true,
    ...config,
  };

  // ...
}
````

Thanks for your work

**Comment by dimadeveatii** [comment]
Thank you for a good suggestion @aleixsuau. It has been added in [this](https://github.com/labs42io/clean-code-typescript/commit/7aecafe532d53748273b77ae13346a2191894750) commit.
