### ISSUE TITLE
Change references from TSLint to ESLint

### ISSUE THREAD

**Issue by mheob** [labs42io/clean-code-typescript#43]
We should change the references from TSLint to ESLint as TSLint has been deprecated as of 2019.

See https://palantir.github.io/tslint:

> :warning:  __TSLint is deprecated.__
> 
> See this issue for more details: [Roadmap: TSLint &rarr; ESLint](https://github.com/palantir/tslint/issues/4534). If you're interested in helping with the TSLint/ESLint migration, please check out our [OSS Fellowship](https://medium.com/palantir/fellowships-for-open-source-developers-3892e6b75ee1) program.

**Comment by dimadeveatii** [comment]
Good catch!  
A PR is welcome 🚀 !

**Comment by mheob** [comment]
I will tackle it in the next few weeks.
