### ISSUE TITLE
"Use getters and setters" - Why would you start with getters & setters?

### ISSUE THREAD

**Issue by bluEEil** [labs42io/clean-code-typescript#47]
I don't understand this rule in the aspect of why would you add a getter / setter for a simple property with not logic?
The example demonstrates exactly how you can always take a regular property and refactor it easily only within the class to use a getter / setter without editing any of the usage of it (getters and setters act like regular properties outside of the class).
So with this in mind, why would you add getter / setter in advance for simple properties without any logic?

**Comment by dashtaki** [comment]
https://stackoverflow.com/a/1568230/2656499
