### ISSUE TITLE
Add const contexts for literal expressions

### ISSUE THREAD

**Issue by MSakamaki** [labs42io/clean-code-typescript#5]
want you to incorporate features that you think are personally wonderful entering from typescript 3.4

https://github.com/labs42io/clean-code-typescript#avoid-side-effects-part-1

The const definition does not block rewriting of the contents of object, but you can handle immutable objects by using `as const`.
(It can be experienced with typescript 3.4.0-dev)

https://github.com/Microsoft/TypeScript/pull/29510

**Comment by dimadeveatii** [comment]
This is a nice one, didn't know about it. 
Let's first wait for it to be in a release and covered with official documentation so that we can reference it.

**Comment by dimadeveatii** [comment]
Fixed in https://github.com/labs42io/clean-code-typescript/pull/26.
