### ISSUE TITLE
Prefer to use base types in some cases

### ISSUE THREAD

**Issue by matvaleriano** [labs42io/clean-code-typescript#51]
I saw in many interviews people that doesn't know that we can access `Type['attribute']` like this. In some cases it's good because typescript will show you where code will break. For example

given we have a type Person

```ts
type Person = {
  id: string;
  name: string;
}
```

many people create specific functions like this

```ts
const getPersonName = (id: string) => {}
```

besides if you change the attribute's type or name it'll not break anything and you'll suffer to find every place to update, but when we use like this below

```ts
const getPersonName = (id: Person['id']) => {}
```

typescript will tell you where code will break.

> There's another cases for whose use the entire type for function parameter instead of use Pick/Omit/etc.

**Comment by dimadeveatii** [comment]
@matvaleriano while your point is a valid improvement and a Typescript syntactic sugar to reference field types, it is not necessarily a _clean code_ improvement.  

From the perspective of maintaining the code clean and readable, both examples are good. While using `id: Person['id']` has some advantages when doing refactorings, the `id: string` wouldn't compile as well if you change the type.
