### ISSUE TITLE
Persian Translation (Farsi)

### ISSUE THREAD

**Issue by imokech** [labs42io/clean-code-typescript#54]
hi 
Could I translate this to Persian language?
[I want to trans](https://github.com/imokech/clean-code-typescript)

**Comment by dimadeveatii** [comment]
@imokech you're welcome to translate. 
Please fork this repo and translate it there.

Once ready, open a PR to link your translation to this page. Here is an example of PR adding the german translation: https://github.com/labs42io/clean-code-typescript/pull/42

**Comment by dimadeveatii** [comment]
Closing this one in favor of https://github.com/labs42io/clean-code-typescript/issues/15
