### ISSUE TITLE
Add a complete example implementation 

### ISSUE THREAD

**Issue by alfonsograziano** [labs42io/clean-code-typescript#56]
Hi! Thank you for this repo, it is really useful :) 

I would like to add a complete example of the use of clean code and clean architecture concepts (by creating for example the backend for a classic note-taking app).

Do you think that could be interesting for the community?

**Comment by dimadeveatii** [comment]
Hi @lokk3d!
This sounds like a good idea, however I think it's beyond the current repo. This repo is based on simple, atomic practices around coding, which are timeless. 

Going with _Clean Architecture_ is the next evolution. A more comprehensive example would require constant maintenance and could become more opinionated.

But feel free to fork this repo or reference it.
