### ISSUE TITLE
Contribution: Clean Code TypeScript as Web Book

### ISSUE THREAD

**Issue by tderflinger** [labs42io/clean-code-typescript#58]
Hi!

Thanks for your great guide to clean coding with TypeScript! I have created a web "e-book" version of your guide with the [HonKit](https://honkit.netlify.app) application. 

You can check out the web version here: https://tderflinger.github.io/clean-code-typescript-ebook/ and the source code here: https://github.com/tderflinger/clean-code-typescript-ebook

So I wanted to ask if you could add a link to my website. Alternatively, I might create a PR with my changes so you can integrate the version with HonKit into your project. What do you think about that?

Best regards,
-Thomas

**Comment by dimadeveatii** [comment]
Thanks @tderflinger, but we don't want to add any external links.
I'm closing this issue for now.
